Terraform WIP
chariotsolutions/aws-examples pull request #3
Opened 2021-07-06 14:51 UTC by EvanWMorton

Porting the IaC stuff from CloudfFormation to Terraform.  This eliminates the .sh files, and extracts the Python from the YML into separate PY files.
The only functionality so far is uploading a file using the signed-url button.  That means we don't yet have the other button working, nor the eponymous lambda that moves files.
Specific questions are marked by xxkdg, but if you have time please look at everything.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apig.tf
> +# Declares the API Gateways.
Nitpick: I'd prefer that it's called `apigateway.tf`.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apig.tf
> +    integration_uri        = "https://${local.static_bucket_name}.s3.${local.aws_region}.amazonaws.com/index.html"
The `s3_bucket` resource gives you two attributes: `bucket_domain_name` and `bucket_regional_domain_name` that will avoid interpolation.

See [https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#attributes-reference]

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apig.tf
> +    integration_uri        = "https://${local.static_bucket_name}.s3.${local.aws_region}.amazonaws.com/js/{name}"
See above.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apig.tf
> +  #source_arn = aws_apigatewayv2_api.api.arn
There's an example of the ARN format [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission#specify-lambda-permissions-for-api-gateway-rest-api).

From the docs for `source_arn`:

> Without this, any resource from principal will be granted permission – even if that resource is from another account.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apig.tf
> +        destination_arn = "arn:aws:logs:${local.aws_region}:567196586496:log-group:api-gateway"
I recommend creating the log group, so that you can control the retention period and reference it directly (check the `cloudwatch_log_group` doc, however, as I recall that the format of the ARN isn't compatible with all usages.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apig.tf
> +        format          = jsonencode(
I recommend adding `path = "$context.path"` to the log.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  # xxkdg For this and the other objects in the static bucket, is this acl too permissive?
This is appropriate for buckets containing static content, even though I think you'll see a red flag in the Console.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +resource "aws_s3_bucket_object" "main_page" {
At some point, replace these three `aws_s3_bucket_object` resources with a single resource using a [for_each](https://www.terraform.io/docs/language/meta-arguments/for_each.html) that's driven by a map defined as a local.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  source = "../static/index.html"
Rather than using filenames relative to the current directory, it's always better to use a reference from `${module.path}`.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +    output_path = "./signed-url-archive.zip"
ditto re paths; see the `archive_file` definition that I have in [this README](https://github.com/kdgregory/aws-misc/blob/dev-terraform/terraform/lambda/README.md).

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
You'll need to attach the `arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole` policy or the Lambda won't be able to write logfiles.

In a production service, you'd actually want to create a more restrictive policy, but for an example the AWS-defined managed policy is fine.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/variables.tf
> +    description = "The name of the function to invoke"
This can be hardcoded in the Lambda config.

2021-07-06 15:31 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/variables.tf
> +variable "signed_url_lambda_name" {
Rather than making this specific to the signed URL Lambda, I would make it the "base name" for everything defined in this script. For example, if it was "Fribble", I would then create Lambdas named "Fribble-SignedURL" and "Fribble-Credentials" (or something like that -- I can't remember the convention that I used in the original example, but suspect it was based on stack name, which you don't have in Terraform).

2021-07-07 20:21 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    integration_uri        = "https://${aws_s3_bucket.static_bucket.bucket_regional_domain_name}/index.html"
Looking at this now, I think I'd refactor a little more, and create a local variable named `static_endpoint` or the like that contains the everything up to the slash, then just use it wherever you reference the bucket.

```
integration_uri = "${static_endpoint}/index.html
```

2021-07-07 20:21 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  # Are those changes OK?
Here's the problem with that: you're telling S3 that the JavaScript files are actually HTML files (because they're all using the same `content-type`).

Even if you use the map key as both filename and S3 index, I think it would help to define your map like this:

```
"index.html" = { "content-type": "text/html; charset=utf-8"},
"js/signed-url.js" = { "content-type": "application/javascript"},  # or whatever the correct MIME type is
# ...
}
```

I don't know if there would be additional attributes that need to be uploaded, so you could reduce to a name -> content-type, but I'd go with the possibility for different values.

2021-07-07 20:21 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
I recommend against using the `managed_policy_arns` property inside the `aws_iam_role` resource: it prevents you from creating separate attachments. You could respond with "well, Lambdas should use inline policies anyway."

2021-07-07 20:21 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
Speaking of which, you'll need to create an inline policy for this Lambda that allows `s3:PutObject`.

2021-07-09 16:18 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
Implemented the first and third in or before commit a532a78.  Will discuss second one with you.

2021-07-09 16:19 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/variables.tf
> +    description = "The name of the function to invoke"
Implemented in or before commit a532a78.

2021-07-09 16:20 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/variables.tf
> +variable "signed_url_lambda_name" {
Implemented in or before commit a532a78.

2021-07-09 17:14 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    integration_uri        = "https://${aws_s3_bucket.static_bucket.bucket_regional_domain_name}/index.html"
Fixed in 4b0fe510d6f99f51f0451544230bea4cf3126bd1 .

2021-07-09 17:15 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  # Are those changes OK?
Fixed in 4b0fe510d6f99f51f0451544230bea4cf3126bd1 .

2021-07-09 17:28 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
Correction on my earlier statement.  On the third comment (involving s3:PutObject), I did _not_ implement it.  The upload already works, presumably because I made the bucket public read/write.  Shall I change that to public read, and create the policy?

2021-07-14 17:09 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
I handled the second comment ("I recommend against") in 50558cc.

2021-07-19 15:41 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +
Changed the bucket to public read only, and created the policies to allow two lambdas to upload.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    name = "agate"
Set this from a variable.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +
A nit-pick: I would put the routes first.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +
I would move the invocation permissions into the Lambda files.

Reason: in a real deployment the Lambdas would be separate modules, and if you're using them a lot with specific types of invokers (API Gateway, SQS, ...) it makes sense to create the permission and/or event source at the same time..

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +
Missing a route for `favicon.ico`

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +output "url-for-index-page" {
All outputs should go in `outputs.tf`

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  acl    = "public-read"
This should be "private": people using the system won't want anybody else to see what they uploaded.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  acl    = "private"
This, on the other hand, could be "public", although it's arguably a good practice to make everything private by default.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +resource aws_s3_bucket_object whatever_static_item {
Nitpick: just call this `static_items`

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/.gitignore
> +*.zip
I would move the `*.zip` entry into `terraform/.gitignore`, because that's the only place that generates ZIPfiles.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +    role          = aws_iam_role.lambda_execution_role.arn
Please use separate execution roles for each Lambda, and/or change the internal identifier of the role to identify which Lambda it belongs to.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +    function_name = "${var.base_lambda_name}-credentials-lambda-function"
No need to add "-lambda-function" to the external name -- the only place you'll see this is in a listing of Lambda functions.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document role_trust_policy {
Needs a different name, maybe `assumed_role_trust_policy`. At first glance I thought it was for the Lambda's execution role.

Perhaps keep the assumed role definitions separate from everything else and introduce with a comment?

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document role_trust_policy {
Looking below, I see your using `credentials-assumed-role`. I would therefore name the trust policy `credentials-assumed-role-trust-policy`, following the convention that all related resources should use the same "base" name.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +  managed_policy_arns = [aws_iam_policy.upload_policy.arn]
Two comments here: first, as I've mentioned before, I don't like using the `managed_policy_arns` property. Second, in the original it used an inline policy, which I prefer in general, and which this version should use for consistency. 

And third, I don't see the `upload_policy` definition anywhere in here; I'm assuming it's shared with the "signed URL" Lambda? This isn't a good practice, as it means that one Lambda may unexpectedly gain or lose permissions due to changes in another.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document credentials_lambda_trust_policy {
Since there are multiple roles, I think it's important that this be named after the execution role.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/lambda.tf
> +resource aws_iam_policy upload_policy {
As above, this should be duplicated (the filename is also misleading).

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/lambdas/credentials-lambda.py
> +    # xxkdg   Will this still be unique?  Is there an easy alternative, e.g. with a name like get_unique_id()?  Should we switch to a different fruit?
There's no need for session names to be unique, and in fact they probably shouldn't be (to assist in forensics). Instead, they should somehow refer back to the "application," so `{context.aws_request_id}` is better. Also, no need to prefix with a fruit.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document credentials_lambda_trust_policy {
Although, if there was _anything_ that I'd share between Lambdas, it would probably be the execution role trust policy.

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +    handler            = "processing-lambda.lambda_handler"
nitpick: consistent indentation

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +resource aws_lambda_permission allow_upload_bucket {
I don't particularly like this name; would prefer something like `upload_bucket_lambda_invocation` (and if the original didn't use a similar name, I'll change it).

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +resource aws_iam_role_policy_attachment processing_lambda_execution_role_upload_attachmentupload {
Also too long a name; `processing_lambda_upload` is sufficient.

Looks like maybe this one and the previous were the victims of a global search/replace?

2021-07-20 18:34 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/variables.tf
> +    default     = "two_bucks_and_lambda"
Cute, although possible to cause confusion to people not familiar with American slang.

2021-07-20 21:07 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    name = "agate"
Fixed in 8b14e3eb1316d65ce27bc617e73336cde64a9ec1

2021-07-20 21:09 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +
Fixed in 8b14e3eb1316d65ce27bc617e73336cde64a9ec1 .

2021-07-20 21:09 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +
Fixed in 8b14e3eb1316d65ce27bc617e73336cde64a9ec1 .

2021-07-20 21:10 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +
Fixed in 8b14e3eb1316d65ce27bc617e73336cde64a9ec1 .

2021-07-20 21:10 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +output "url-for-index-page" {
Fixed in 8b14e3eb1316d65ce27bc617e73336cde64a9ec1 .

2021-07-20 21:15 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  acl    = "private"
I will leave this private based on the Principle of Least Privilege, or perhaps a restatement of that principle from the point of view of the resource.

2021-07-21 20:43 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apig.tf
> +        format          = jsonencode(
Did this a while back.

2021-07-21 20:44 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +resource "aws_s3_bucket_object" "main_page" {
Did this a while back.

2021-07-21 20:48 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +  acl    = "public-read"
Done in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:48 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/buckets.tf
> +resource aws_s3_bucket_object whatever_static_item {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:49 UTC, EvanWMorton commented on two_buckets_and_a_lambda/.gitignore
> +*.zip
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:49 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +    role          = aws_iam_role.lambda_execution_role.arn
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:49 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +    function_name = "${var.base_lambda_name}-credentials-lambda-function"
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:50 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document role_trust_policy {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:50 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +  managed_policy_arns = [aws_iam_policy.upload_policy.arn]
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:51 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document credentials_lambda_trust_policy {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:51 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +data aws_iam_policy_document credentials_lambda_trust_policy {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:52 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/lambdas/credentials-lambda.py
> +    # xxkdg   Will this still be unique?  Is there an easy alternative, e.g. with a name like get_unique_id()?  Should we switch to a different fruit?
Nor to suffix with a vegetable?  Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:54 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/lambda.tf
> +resource aws_iam_policy upload_policy {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.  And lambda.tf is gone.

2021-07-21 20:54 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +    handler            = "processing-lambda.lambda_handler"
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:55 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +resource aws_lambda_permission allow_upload_bucket {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:55 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +resource aws_iam_role_policy_attachment processing_lambda_execution_role_upload_attachmentupload {
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.

2021-07-21 20:57 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/variables.tf
> +    default     = "two_bucks_and_lambda"
Fixed in or before fa9930b080a5bf10cb7b46bc2830f4e5a6340e6d.
It wasn't actually a joke.  At certain points some identifiers were too long, so I shortened the base but with an attempt at recognizability.  Now that the length problems have been fixed elsewhere, this can go back to normal.

2021-08-02 13:38 UTC, kgregory-chariot requested changes
Definitely getting close.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/main.tf
> +    bucket_name_base = "com-chariotsolutions-emortontf"
This needs to be passed in as a variable, with no default.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    route_key = "GET /favicon.ico"
I think you can create a catch-all route using a route key like this:

```
route_key = "GET /{proxy+}"
```

Then, the integration would reference that with:

```
integration_uri        = "${local.static_root}/{proxy}"
```

This could replace the configuration for both `favicon.ico` and the JavaScript sources.

See https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    name = "two_buckets_and_a_lambda_log_group"
Two comments:

1. I've gotten into the habit of naming log groups with a leading "path" component that describes where the logs are coming from; in this case, `/apigateway/`. It makes it a lot easier to find log groups when you have a lot of services.
2. You don't need the `_log_group` suffix at the end, although it might make sense to either suffix with `_access_log` or use a more complete path: `/apigateway/access/two_buckets_and_a_lambda`.
3. Use `var.api_gateway_name` rather than a hardcoded name.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +# Declares the lambda for credentials.js.
You should create a CloudWatch log group for the Lambda, otherwise it will create one itself and leave litter behind when the stack is destroyed.

This group must have the name `/aws/lambda/LAMBDA_NAME` (see comment below).

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +    function_name = "${var.base_lambda_name}_credentials"
The Lambda name should be defined as a local, so that it can be reused for the log group (important) and execution role (less important) names.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +  name               = "${var.base_lambda_name}_lambda_exec_role_${local.aws_region}"
OK, make that "more important" for using the Lambda's name ;-)

Nitpick: I don't think you need `_lambda` in the role's name. You could use `/lambda/` as the role's path, just for organization (unlike other things, role paths are ignored), but I never do that so I'm not going to recommend it.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +resource aws_iam_role credentials_assumed_role {
Please add a `name` property to the role definition, based on the Lambda's name.

If you don't, then I believe that Terraform will generate a name with random content, which will be confusing to anyone looking at their list of roles.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/credentials-lambda.tf
> +    name = "anameisrequired"
I wasn't aware that you could omit the name for an inline policy (maybe a Terraform bug?).

It should use the same name as the CloudFormation example (I'd like to keep all names the same between these examples, but I'm pretty sure that I didn't add region to the role names ... that will be another pass).

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/lambdas/credentials-lambda.py
> +    # The old code to assign session_name, now commented out, produced long session names like
Can remove this comment.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +# Declares the lambda that does the "processing," which
Same comments apply re names and creating log group as for the other Lambdas.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/processing-lambda.tf
> +    policy_arn = aws_iam_policy.process_read_from_upload_policy.arn
I would prefer that this is an inline policy.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/signed-url-lambda.tf
> +# Declares the lambda for signed-url.js.
Same comments apply wrt names and log groups.

2021-08-02 13:38 UTC, kgregory-chariot commented on two_buckets_and_a_lambda/terraform/variables.tf
> +    default     = "agate"
Also set the default to `two_buckets_and_a_lambda`.

2021-08-02 18:40 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    route_key = "GET /favicon.ico"
It also replaces the config for the main page, so long as I put the name of the file index.html in:
```
output url-for-index-page {
  value = "${aws_apigatewayv2_api.api.api_endpoint}/index.html"
}
```
(This change will be in my next push.)

2021-08-03 15:42 UTC, EvanWMorton commented on two_buckets_and_a_lambda/terraform/apigateway.tf
> +    name = "two_buckets_and_a_lambda_log_group"
You'll see that I named it a mix of your two suggestions in comment # 2.

2021-09-02 21:18 UTC, kgregory-chariot approved these changes

2021-09-02 21:19 UTC, kgregory-chariot commented
LGTM

2021-09-02 21:22 UTC, merged